### ISSUE TITLE
applicazione per sito web

### ISSUE THREAD

**Issue by Obitech96** [iamluciano/flutter-webapp#2]
ciao, dato il tuo nome immagino anche tu sia Italiano
ho bisogno di creare un'app che racchiuda il mio sito internet
ho provato ad utilizzare il tuo progetto, ma senza risultato; riusciresti a darmi una mano ad inizializzare il progetto dato che ci sto sbattendo la testa da ore se non da giorni?
saluti 
Marco

**Comment by lucianoiam** [comment]
Ciao, non sono certamente italiano ma ci capiamo. Questa "template app" richiede qualche esperienza nello sviluppo Flutter, non è stata progettata come una soluzione automatica. Hai una domanda particolare?
